### PR TITLE
Added a method to cancel the scheduled OneSignal notifications

### PR DESCRIPTION
**Pull request by zzeebbii**
Notification can be cancelled by passing the ID of it. Delete method is also added as it requires a DELETE HTTP method to cancel a notification

### CODE REVIEW

**Comment by LaravDev** [comment]
This is great, but i have a question, how do you get the Notification ID? when we create a new notification, how do we store that specific ID, so we can use it in the future to delete it? Thanks in advance

**Comment by zzeebbii** [comment]
@LaravDev Actually none of the method is returning the results from OneSignal except `SendCustomNotification`. I'll add a method to get response from OneSignal and Will add a merge request again. I was away but now I'm back :-)

**Comment by LaravDev** [comment]
@zzeebbii That's great!, thanks for your efforts!

**Comment by LaravDev** [comment]
@zzeebbii so, if i use the SendCustomNotification, i'll get all the data back from OneSignal? how? sorry for asking

**Comment by zzeebbii** [comment]
@LaravDev Yes, `SendCustomNotification` returns a Guzzle response. You can use it's `getBody` method to read the response from OneSignal.

**Comment by LaravDev** [comment]
@zzeebbii sorry for asking, but i just can't figure out how to get the notification id to cancel it later, can please kindly show an example of how could this be done with SendCustomNotification? thanks in advance!

**Comment by LaravDev** [comment]
Nevermind, i did it!, and thanks anyway!

**Pull request merged**
