### PR TITLE
add badges counter for iOS devices

### PR DESCRIPTION
**Pull request by almatri**
For iOS apps , to increase the notification icon badge number we have to set two parameters

    'ios_badgeType' = 'Increase';
    'ios_badgeCount' = 1;

### CODE REVIEW

**Comment by berkayk** [comment]
I am not sure that this feature should be integrated like this. Some developers might not want this feature at all and it's impossible to configure with the given commit. You can implement the same behavior with the newly added methods that enable this feature.

**Comment by almatri** [comment]
you're right about the part that it's impossible to configure it in this way. But the problem is the badge counter is already implemented by defaults for Android devices and handled by OneSignal but for iOS we have to handle it manually.

See this comment from OneSignal documentations
"Badges - shows the number of notifications outstanding. Note: Android badges are automatically handled by OneSignal."
https://documentation.onesignal.com/reference#section-appearance

what do you think?

**Comment by raphaelmsr** [comment]
Any update ?

**Comment by orlandocharles** [comment]
@raphaelmsr I think you can use this method. All notification methods like `sendNotificationCustom` goes through `sendNotificationCustom`

```
OneSignal::sendNotificationCustom($parameters);
```

**Pull request closed without merging**
